### ISSUE TITLE
android 获取权限后直接闪退

### ISSUE THREAD

**Issue by ZmlWll** [hetian9288/flutter_qr_reader#39]
java.lang.NoSuchMethodError: No static method open(I)Lcom/google/zxing/client/android/camera/open/OpenCamera; in class Lcom/google/zxing/client/android/camera/open/OpenCameraInterface; or its super classes (declaration of 'com.google.zxing.client.android.camera.open.OpenCameraInterface' appears in /data/app/com.xxx.xxxx-xxxxx==/base.apk)
        at com.google.zxing.client.android.camera.CameraManager.openDriver(CameraManager.java:107)
        at me.hetian.flutter_qr_reader.readerView.QRCodeReaderView.surfaceCreated(QRCodeReaderView.java:225)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:709)
        at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:144)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2433)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1452)
        .......

**Comment by gausoft** [comment]
Having the same issue

**Comment by liangtian123** [comment]
Having the same issue

**Comment by mulieli** [comment]
怎么解决的？
