### ISSUE TITLE
Zxing version

### ISSUE THREAD

**Issue by hrxiang** [hetian9288/flutter_qr_reader#63]
E/AndroidRuntime(10598): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(10598): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
E/AndroidRuntime(10598): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
E/AndroidRuntime(10598): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
E/AndroidRuntime(10598): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(10598): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
E/AndroidRuntime(10598): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/AndroidRuntime(10598): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/AndroidRuntime(10598): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(10598): Caused by: java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
E/AndroidRuntime(10598): 	at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:624)
E/AndroidRuntime(10598): 	at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
E/AndroidRuntime(10598): 	at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
E/AndroidRuntime(10598): 	at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
E/AndroidRuntime(10598): 	at me.hetian.flutter_qr_reader.reader.MyMultiFormatReader.decodeInternal(MyMultiFormatReader.java:157)
E/AndroidRuntime(10598): 	at me.hetian.flutter_qr_reader.reader.MyMultiFormatReader.decode(MyMultiFormatReader.java:55)
E/AndroidRuntime(10598): 	at me.hetian.flutter_qr_reader.readerView.QRCodeReaderView$DecodeFrameTask.doInBackground(QRCodeReaderView.java:409)
E/AndroidRuntime(10598): 	at me.hetian.flutter_qr_reader.readerView.QRCodeReaderView$DecodeFrameTask.doInBackground(QRCodeReaderView.java:380)
E/AndroidRuntime(10598): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
E/AndroidRuntime(10598): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(10598): 	... 4 more

**Comment by hrxiang** [comment]
flutter_qr_reader: ^1.0.4
